### ISSUE TITLE
Signature calculation problem 

### ISSUE THREAD

**Issue by RenePierre89** [lyra/aspnet-payment-form-examples#1]
I am facing a signature calculation issue and cannot say that the support is of much help at this time. I took the code as is to test locally but could someone calculate the signature for me with the following information so that I can compare the result? 

SecretKey : 1d************Pc

Datas : (deleted by moderator)

PS : Do not forget to decode the different values. 

Thanks in advance !

**Comment by nabil509** [comment]
Hi @RenePierre89,

Sorry for the delay. We started recently working on this sample project. We are about to refactor code and upgrade it to work with recent MS Framework versions.

Have you resolved your problem? 

PS: I edited your message to mask the posted **secret key**. Please avoid to post sensitive data here.

**Comment by RenePierre89** [comment]
Hello, 

Yes I was able to find a solution. 
The problem was the order of the parameters.

As soon as I posted my message, I changed the key to our client.
